spring.application.name=userservice
server.port=0

spring.kafka.bootstrap-servers=localhost:9092,localhost:9094,localhost:9096
spring.kafka.producer.serializer.key=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.serializer.value=org.springframework.kafka.support.serializer.JacksonJsonSerializer
spring.kafka.producer.config.acks=all

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=password
spring.jpa.show-sql=true